sudo: required
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - cp .travis.maven.settings.xml $HOME/.m2/settings.xml
  - git clone https://github.com/Sammers21/vertx-cassandra-client
  - cd vertx-cassandra-client
  - git checkout with_codegen
  - mvn clean install -Dmaven.test.skip=true -s .travis.maven.settings.xml
  - cd ..

script:
  - set -e
  - ./gradlew build